// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO1z6tHlf7eNK6Z3ib3Y48ci8YHc3QjDk',
    appId: '1:514438827672:web:aec3c5f1c4127dd3428aed',
    messagingSenderId: '514438827672',
    projectId: 'blood-sync1',
    authDomain: 'blood-sync1.firebaseapp.com',
    storageBucket: 'blood-sync1.appspot.com',
    measurementId: 'G-79V0KLX8W9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOzB17iHpSNXHCYbc06Pc6kBaxIqDQmbE',
    appId: '1:514438827672:android:fa42f36517887d9c428aed',
    messagingSenderId: '514438827672',
    projectId: 'blood-sync1',
    storageBucket: 'blood-sync1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFPoziXBQb6cYH1TqkaWwej-KJIImCYIY',
    appId: '1:514438827672:ios:121f7e8d0e267650428aed',
    messagingSenderId: '514438827672',
    projectId: 'blood-sync1',
    storageBucket: 'blood-sync1.appspot.com',
    iosBundleId: 'com.example.bloodSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFPoziXBQb6cYH1TqkaWwej-KJIImCYIY',
    appId: '1:514438827672:ios:121f7e8d0e267650428aed',
    messagingSenderId: '514438827672',
    projectId: 'blood-sync1',
    storageBucket: 'blood-sync1.appspot.com',
    iosBundleId: 'com.example.bloodSync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO1z6tHlf7eNK6Z3ib3Y48ci8YHc3QjDk',
    appId: '1:514438827672:web:82bfc46bf3d3c69e428aed',
    messagingSenderId: '514438827672',
    projectId: 'blood-sync1',
    authDomain: 'blood-sync1.firebaseapp.com',
    storageBucket: 'blood-sync1.appspot.com',
    measurementId: 'G-5FEWBQPDGT',
  );

}